config/routes.rb
RedditClone::Application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :subs
  resources :links, except: :index do
    resources :comments, only: [:show, :create]
  end

  post '/comments/:id', to: "comments#reply", as: :comment_reply

  root to: "subs#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :text, :link_id, :parent_comment_id, :user_id

  validates :text, :link_id, :user_id, presence: true

  belongs_to :user,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id

  belongs_to :link,
  class_name: "Link",
  foreign_key: :link_id,
  primary_key: :id

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :title, :url, :text, :user_id

  validates :title, :url, :user_id, presence: true
  validates :url, uniqueness: true

  belongs_to :submitter,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id

  has_many :link_subs,
  class_name: "LinkSub",
  foreign_key: :link_id,
  primary_key: :id

  has_many :subs,
  through: :link_subs,
  source: :sub

  has_many :comments,
  class_name: "Comment",
  foreign_key: :link_id,
  primary_key: :id

  def comments_by_parent_id
    comments = self.comments
    hash = Hash.new{ |h,k| h[k] = [] }
    comments.each do |comment1|
      hash[nil] << comment1 if comment1.parent_comment_id.nil?
      comments.each do |comment2|
        hash[comment1.id] << comment2 if (comment1.id == comment2.parent_comment_id)
      end
    end

    hash
  end

end

app/models/link_sub.rb
class LinkSub < ActiveRecord::Base
  attr_accessible :link_id, :sub_id

  belongs_to :link,
  class_name: "Link",
  foreign_key: :link_id,
  primary_key: :id

  belongs_to :sub,
  class_name: "Sub",
  foreign_key: :sub_id,
  primary_key: :id

end

app/models/sub.rb
class Sub < ActiveRecord::Base
  attr_accessible :name, :user_id

  validates :name, :user_id, presence: true
  validates :name, uniqueness: true

  belongs_to :moderator,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id

  has_many :link_subs,
  class_name: "LinkSub",
  foreign_key: :sub_id,
  primary_key: :id

  has_many :links,
  through: :link_subs,
  source: :link

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :session_token

  before_validation(:ensure_session_token, on: :create)
  validates :username, :password_digest, presence: true
  validates :username, uniqueness: true

  has_many :subs,
  class_name: "Sub",
  foreign_key: :user_id,
  primary_key: :id

  has_many :links,
  class_name: "Link",
  foreign_key: :user_id,
  primary_key: :id

  has_many :comments,
  class_name: "Comment",
  foreign_key: :user_id,
  primary_key: :id


  def self.find_by_credentials(username, password)
    @user = User.find_by_username(username)

    if @user && @user.is_password?(password)
      @user
    else
      nil
    end
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token = SecureRandom.urlsafe_base64(16)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def sign_in(user)
    session[:session_token] = user.reset_token!
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(params[:comment])
    @comment.user_id = current_user.id
    @comment.link_id = params[:link_id]

    if @comment.save
      redirect_to link_url(params[:link_id])
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to link_url(params[:link_id])
    end
  end

  def show
    @link = Link.find(params[:link_id])
    @comment = Comment.find(params[:id])
    @comments_by_parent_id = @link.comments_by_parent_id
  end

  def reply
    @parent_comment = Comment.find(params[:id])

    @comment = Comment.new(params[:comment])
    @comment.user_id = current_user.id

    @comment.link_id = @parent_comment.link_id
    @comment.parent_comment_id = @parent_comment.id

    if @comment.save
      redirect_to link_url(@comment.link_id)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to link_url(@comment.link_id)
    end
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def new
    @link = Link.new
    @subs = Sub.all
  end

  def create
    @link = Link.new(params[:link])
    @link.user_id = current_user.id
    @link.sub_ids = params[:subs]

    if @link.save
      redirect_to link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      render :new
    end
  end

  def show
    @link = Link.find(params[:id])
    @comments_by_parent_id = @link.comments_by_parent_id
  end

  def edit
    @link = Link.find(params[:id])
    @subs = Sub.all
  end

  def update
    @link = Link.find(params[:id])
    @link.sub_ids = params[:subs]

    if @link.update_attributes(params[:link])
      redirect_to link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      render :edit
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to subs_url
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_credentials(
                                params[:user][:username],
                                params[:user][:password]
                                )

    if @user
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = "Incorrect user/password combo"
      render :new
    end
  end

  def destroy
    current_user.reset_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_filter :ensure_moderator, only: :edit

  def ensure_moderator
    sub = Sub.find(params[:id])
    redirect_to sub_url(sub) unless sub.moderator == current_user
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(params[:sub])
    @sub.links.new(params[:links].values)
    @sub.links.reject!{ |link| link.title.empty? }
    @sub.links.each { |link| link.submitter = current_user }
    @sub.moderator = current_user

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update_attributes(params[:sub])
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% if comments_by_parent_id[nil].include?(comment) %>

<ul>
  <li><%= comment.text %><%= button_to "Reply", link_comment_url(comment.link, comment) %>
</li>

  <% comments_by_parent_id[comment.id].each do |child| %>


        <% new_hash = comments_by_parent_id.merge(
        {nil => comments_by_parent_id[comment.id]}
        ) %>

        <%= render partial: "comments/comment", locals:
        {comment: child, comments_by_parent_id: new_hash }
        %>

  <% end %>

</ul>
<% end %>

app/views/comments/show.html.erb
<%= render "comment", locals: {comment: @comment, comments_by_parent_id: @comments_by_parent_id} %>

<h4>Add Comment</h4>
<form action="<%= comment_reply_url(@comment) %>" method="post">

    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Body<input type="text" name="comment[text]"></label>

    <input type="submit" value="Submit Comment">

</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:errors] if flash[:errors] %>

<% if current_user %>
  Signed in as <%= current_user.username %>
  <%= button_to "Sign Out", session_url, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_session_url %>
  <%= link_to "Sign Up", new_user_url %>
<% end %>

<%= yield %>

</body>
</html>

app/views/links/_link.html.erb
<h3>Link Show Page: <%= link_to link.title, link_url(link) %><h3>
<h3>Actual Link: <%= link_to link.url, link.url %><h3>
<h3>Link Note: <%= link.text %></h3>

app/views/links/edit.html.erb
<h1>Edit a link!</h1>

<form action="<%= link_url(@link) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="hidden" name="_method" value="put">

  <label>
    Link Title:
    <input type="text" name="link[title]" value="<%= @link.title %>">
  </label>
  <br>
  <label>
    Link URL:
    <input type="text" name="link[url]" value="<%= @link.url %>">
  </label>
  <br>
  <label>
    Link Note:
    <input type="text" name="link[text]" value="<%= @link.text %>">
  </label>
  <br>

    <h5>Which subs do you want to add this to?</h5>

    <% @subs.each do |sub| %>

    <input type="checkbox"
      name="subs[]"
      value="<%= sub.id %>"
      <%= "checked" if @link.subs.include?(sub) %>>
    <%= sub.name %>
    <br>
    <% end %>

    <input type="hidden" name="subs[]" value="">

  <input type="submit" value="Edit Link">

</form>

app/views/links/new.html.erb
<h1>Add a link!</h1>

<form action="<%= links_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Link Title:
    <input type="text" name="link[title]" value="">
  </label>
  <br>
  <label>
    Link URL:
    <input type="text" name="link[url]" value="">
  </label>
  <br>
  <label>
    Link Note:
    <input type="text" name="link[text]" value="">
  </label>
  <br>

    <h5>Which subs do you want to add this to?</h5>

    <% @subs.each do |sub| %>

    <input type="checkbox" name="subs[]" value="<%= sub.id %>"><%= sub.name %>
    <br>
    <% end %>

  <input type="submit" value="Add Link">

</form>

app/views/links/show.html.erb
<%= render @link %>

<h3>Subs</h3>
<ul>
<% @link.subs.each do |sub| %>
<li><%= link_to sub.name, sub_url(sub) %></li>
<% end %>
</ul>

<h3><%= link_to "Edit Link", edit_link_url(@link)%></h3>
<%= button_to "Delete Link", link_url(@link), method: :delete %>

<h4>Comments</h4>

<% @link.comments.each do |comment| %>
  <%# @comment = comment %>
  <%= render partial: "comments/comment", locals:
  {comment: comment, comments_by_parent_id: @comments_by_parent_id}
  %>
<% end %>

<h4>Add Comment</h4>
<form action="<%= link_comments_url(@link) %>" method="post">

    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <input type="text" name="comment[text]">
    <br>
    <input type="submit" value="Submit Comment">

</form>

app/views/subs/_sub.html.erb
<h1>Sub Name: <%= link_to sub.name, sub_url(sub) %></h1>

<%= button_to "Delete Sub", sub_url(sub), method: :delete %>

app/views/subs/edit.html.erb
<h1><%= @sub.name %></h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="put">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <br>
  <label>
    Sub name:
    <input type="text" name="sub[name]" value="<%= @sub.name %>">
  </label>

  <input type="submit" value="Edit Sub">

</form>

app/views/subs/index.html.erb
<%= render @subs %>

app/views/subs/new.html.erb
<h1>Create new sub!</h1>

<form action="<%= subs_url %>" method="post">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Sub name:
    <input type="text" name="sub[name]" value="">
  </label>

  <br><br>

  Submit up to 3 links! (Optional)
  <br><br>
  <label>
    Link Title:
    <input type="text" name="links[1][title]">
  </label>
  <br>
  <label>
    Link URL:
    <input type="text" name="links[1][url]">
  </label>
  <br>
  <label>
    Link Note:
    <input type="text" name="links[1][text]">
  </label>

  <br><br>
  <label>
    Link Title:
    <input type="text" name="links[2][title]">
  </label>
  <br>
  <label>
    Link URL:
    <input type="text" name="links[2][url]">
  </label>
  <br>
  <label>
    Link Note:
    <input type="text" name="links[2][text]">
  </label>

  <br><br>
  <label>
    Link Title:
    <input type="text" name="links[3][title]">
  </label>
  <br>
  <label>
    Link URL:
    <input type="text" name="links[3][url]">
  </label>
  <br>
  <label>
    Link Note:
    <input type="text" name="links[3][text]">
  </label>
  <br>

  <input type="submit" value="Create sub!">

</form>

app/views/subs/show.html.erb
<%= render @sub %>

<h1>Links</h1>
<%= render @sub.links %>

<%= link_to "Edit Sub", edit_sub_url(@sub) if current_user == @sub.moderator %>

app/views/users/new.html.erb
<h1>Create a user</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Username:
    <input type="text" name="user[username]" value="">
  </label>

  <br>

  <label>
    Password:
    <input type="password" name="user[password]" value="">
  </label>

  <br>

  <input type="submit" value="Create User">

</form>

app/views/users/show.html.erb
Hello!